server:
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 10

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Shiro
shiro:
  user:
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30


mybatis:
  mapper-locations: classpath*:mapper/*.xml

#多数据源 1主1从
datasource:
 #从库数量
  readSize: 1
  #不使用druid数据源 - mybatis-plus跟druid没有兼容好
  #com.alibaba.druid.pool.DruidDataSource
  type: com.zaxxer.hikari.HikariDataSource
#主库
  write:
    jdbcUrl: jdbc:mysql://localhost:3306/business?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: spkzq521
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 100
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQueryTimeout: 900000
    validationQuery: SELECT SYSDATE() from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: -1
  read1:
    jdbcUrl: jdbc:mysql://localhost:3306/business?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: sandman
    password: spkzq521
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 100
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQueryTimeout: 900000
    validationQuery: SELECT SYSDATE() from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: -1
# JetCache config
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100